/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vl4ds4m_objdetjfx_Detector */

#ifndef _Included_org_vl4ds4m_objdetjfx_Detector
#define _Included_org_vl4ds4m_objdetjfx_Detector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vl4ds4m_objdetjfx_Detector
 * Method:    getBoundedBoxes
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_vl4ds4m_objdetjfx_Detector_getBoundedBoxes
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
